swagger: '2.0'
info:
  description: API definition of CloudTrail-Tracker
  version: 1.0.0
  title: Swagger CloudTrail-Tracker
  contact:
    email: joprfon@inf.upv.es
basePath: '/{stage}/cloudtracking_querys'
tags:
  - name: scan
    description: General query
  - name: services
    description: General services query
  - name: users
    description: Information about user actions
schemes:
  - http
paths:
  /scan:
    get:

        tags:
          - scan
        summary: General query, no user or service filter
        description: General query, no user or service filter
        operationId: scan
        produces:
          - application/json
        parameters:
        - name: eventName
          in: query
          description: Event name to filter
          required: false
          type: string
        - name: count
          in: query
          description: Return a number instead a json
          required: false
          default: false
          type: boolean
        - name: from
          in: query
          description: Date to start. YYYY-MM-DD or YYYY-MM-DDTHH-MM (%Y-%m-%dT%H:%M:%S)
          required: false
          type: string
        - name: to
          in: query
          description: Date to end. YYYY-MM-DD or YYYY-MM-DDTHH-MM (%Y-%m-%dT%H:%M:%S)
          required: false
          type: string
        - name: params
          in: query
          description: A comma-separated list of extra parameter to search (column). See /parameters to get more info.
          required: false
          type: array
          items:
            type: string
        - name: values
          in: query
          description: A comma-separated list of extra parameter to search (column).
          required: false
          type: array
          items:
            type: string
        responses:
          '200':
            description: successful operation
            schema:
              $ref: '#/definitions/item_object'
  /parameters:
    get:

      summary: List all available parameters to query
      description: List all available parameters to query
      operationId: parametersList
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              type: string
  /services:
    get:
      tags:
        - services
      summary: List all services
      description: List all services
      operationId: servicesList
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              type: string
  '/services/{service}':
    get:
      tags:
        - services
      summary: Finds information from a service
      description: Multiple status values can be provided with comma separated strings
      operationId: services
      produces:
        - application/json
      parameters:
        - name: service
          in: path
          description: Name of service to find
          required: true
          type: string
        - name: eventName
          in: query
          description: Event name to filter
          required: false
          type: string
        - name: count
          in: query
          description: Return a number instead a json
          required: false
          default: false
          type: boolean
        - name: from
          in: query
          description: Date to start. YYYY-MM-DD or YYYY-MM-DDTHH-MM (%Y-%m-%dT%H:%M:%S)
          required: false
          type: string
        - name: to
          in: query
          description: Date to end. YYYY-MM-DD or YYYY-MM-DDTHH-MM (%Y-%m-%dT%H:%M:%S)
          required: false
          type: string
        - name: params
          in: query
          description: A comma-separated list of extra parameter to search (column). See /parameters to get more info.
          required: false
          type: array
          items:
            type: string
        - name: values
          in: query
          description: A comma-separated list of extra parameter to search (column).
          required: false
          type: array
          items:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/item_object'
  /users:
    get:
      tags:
        - users
      summary: List all users
      description: List all users
      operationId: usersList
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              type: string
  '/users/{user}':
    get:
      tags:
        - users
      summary: List events from an user
      operationId: user
      produces:
        - application/json
      parameters:
        - name: user
          in: path
          description: name of service to find
          required: true
          type: string
        - name: eventName
          in: query
          description: Event name to filter
          required: false
          type: string
        - name: count
          in: query
          description: Return a number instead a json
          required: false
          type: boolean
        - name: from
          in: query
          description: Date to start. YYYY-MM-DD or YYYY-MM-DDTHH-MM (%Y-%m-%dT%H:%M:%S)
          required: false
          type: string
        - name: to
          in: query
          description: Date to end. YYYY-MM-DD or YYYY-MM-DDTHH-MM (%Y-%m-%dT%H:%M:%S)
          required: false
          type: string
        - name: params
          in: query
          description: A comma-separated list of extra parameter to search (column). See /parameters to get more info.
          required: false
          type: array
          items:
            type: string
        - name: values
          in: query
          description: A comma-separated list of extra values to search (value).
          required: false
          type: array
          items:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/item_object'
definitions:
  item_object:
    type: array
    items:
      type: object
      properties:
        eventTime:
          type: string
        eventSource:
          type: string
        userIdentity_userName:
          type: string
        eventID:
          type: string
        eventName:
          type: string

